### ISSUE TITLE
Map Legend and Land Use Colors

### ISSUE THREAD

**Issue by dwvieira** [NYCPlanning/labs-zola#498] opened 2018-02-20 20:59 UTC
#### User Story
As an applicant, I want to be able to export a land use map from ZoLa with a legend presenting the land use colors. This was an available feature in the old version of ZoLA. 

#### Description
What's it all about?
The old version of ZoLa allowed users to export a map with a legend for the land uses. This is not available in the new version.

#### What should happen:
Printing the map should include the legend.

#### What happened instead:
The printed map only provides the lot and neighborhood information.

#### How to reproduce this bug:

1. Select a lot in ZoLA.
2. Navigate to File->Print 
3. The print preview does not include a legend. It only provides the lot and neighborhood information.

**Comment by trbmcginnis** [comment] 2018-09-13 18:39
duplicate of #347

**Closed by trbmcginnis** 2018-09-13 18:39 UTC
Labels: enhancement, feedback
