### ISSUE TITLE
Add Industrial Business Zones

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/labs-zola#436] opened 2017-12-01 19:45 UTC
At a Carto conference and there is demand for this data to be included in ZoLA

**Comment by chriswhong** [comment] 2017-12-02 02:47
Is it published anywhere?  I believe EDC maintains this, right?

**Comment by AmandaDoyle** [comment] 2017-12-05 21:59
From what I've found only as a list of block and lots for each zone published as pdfs here:
https://www.nycedc.com/industry/industrial/nyc-industrial-business-zones

**Comment by smithsj** [comment] 2017-12-22 01:15
I was looking for this today too and couldn't find it...what's going on here? Blocks and lots are online, but in that PDF form (why??), and since BBLs change (when lots are merged and split), the is basically impossible to trust.

**Comment by andrewmartini** [comment] 2018-01-08 13:50
Getting shapefiles of the IBZs has always been a problem, but they definitely exist - city agencies do in fact posses this dataset

**Comment by paul-chung** [comment] 2018-01-09 20:20
Would it also be possible to add in the subarea 1 and subarea 2 classifications within IBZs as per the latest [Storage Text Amendment Appendix J](https://www1.nyc.gov/assets/planning/download/pdf/plans-studies/self-storage-special-permit-ibz/cc-adopted-text-amendment-a.pdf) when adding the IBZ overlay? 

Does the next sprint label mean that the inclusion of the IBZ layer will be part of the next update to the Zola map?

**Comment by chriswhong** [comment] 2018-01-10 04:17
No @paul-chung , there is no plan to add IBZs until the source dataset is made public by the EDC.

**Comment by alissarose** [comment] 2018-02-07 23:51
helllllo! here's a file I scraped together.

process:
1. download all pdfs from [EDC](https://www.nycedc.com/industry/industrial/nyc-industrial-business-zones)
2. merge all pages in adobe acrobat
3. convert to excel from acrobat
4. clean/massage/love in numbers (😱)

^ meaning if there's any errors, lmk and I'm happy to rectify with master spreadsheet (also attached in zip
[nyc_ibz_all_02072018.zip](https://github.com/NYCPlanning/labs-zola/files/1705176/nyc_ibz_all_02072018.zip)
)

**Comment by michellemho** [comment] 2018-02-08 17:40
Annnnd joined to geometries here! These are 2013 IBZs joined with 2015 MAPPLUTO tax lots... not ideal, so proceed with caution.

[nyc_ibz_all.geojson.zip](https://github.com/NYCPlanning/labs-zola/files/1708151/nyc_ibz_all.geojson.zip)

**Comment by chriswhong** [comment] 2018-02-11 23:09
@michellemho @alissarose I tinkered with the same approach of scraping data from the block/lot lists and dissolving the results, but it doesn't quite fit the boundaries as they exist in the printed maps EDC hosts (and thus misleading to add to ZoLa.) We need the shapefile.

**Comment by jamesmlloyd** [comment] 2018-02-21 15:29
Designated M Zones is an alternative geography that could be used as per Paul Chung's comment. DCP owns the Designated M Zones shapefile, so it could make it public on Bytes of the Big Apple and then you all could put it up on ZoLa. The Designated M Zones are a "text map" in zoning parlance, which is the same type of geography as MIHAs, IHAs, the Transit Zone, etc.

**Comment by lblok** [comment] 2018-03-07 21:18
@jamesmlloyd Could you explain more about what you mean by Designated M Zones? I've never heard of those in the zoning text--just M zoning districts, from the actual Zoning Map.

**Comment by jamesmlloyd** [comment] 2018-03-07 22:36
@lblok When the City passed the recent zoning changes for the IBZs to institute a CPC special permit for self-storage, DCP created "Designated Areas Within Manufacturing Districts," which almost exactly mirror the IBZs. See Appendix J of the ZR. Amanda Eyer at DCP has these shapefiles, as she provided them to us during ULURP. I don't know why DCP hasn't published them online yet.

While EDC is the final word on what's within IBZs, the designated areas within manufacturing districts (designated M-zones for short) are an actual zoning text map and therefore should be made publicly available by DCP and also published on ZoLa.

**Comment by lblok** [comment] 2018-03-07 23:31
Great, that’s very helpful. I will try to get in touch with her. Are you
able to share the shapefile that you have?

**Comment by paul-chung** [comment] 2018-03-27 19:53
@chriswhong @jamesmlloyd @lblok Just wanted to follow up with you all to see if there was any updates to the IBZ / Designated M-Zone feature on the ZoLa map. Thanks in advance!

**Comment by chriswhong** [comment] 2018-05-02 01:32
The NYC EDC has published the IBZ shapefile! I'll see if we can get a layer into ZoLa this week.
https://www.nycedc.com/industry/industrial/nyc-industrial-business-zones

**Comment by lblok** [comment] 2018-05-02 14:52
I meant to post this earlier, but James kindly shared the Designated Areas within M Zones shapefile that DCP used during the ULURP process. This one should be more precise than the EDC one, though I haven't spot checked. I know the differences are very minimal. 
[Designated_MDistricts_V3_FinalDraft.zip](https://github.com/NYCPlanning/labs-zola/files/1967718/Designated_MDistricts_V3_FinalDraft.zip)

**Closed** 2018-05-04 19:47 UTC
Labels: blocked, in progress
