### ISSUE TITLE
Map tiles are highlighted when admin boundaries are turned on

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#774] opened 2019-02-05 19:32 UTC
Steps to reproduce:
- Load zola
- Turn off other colorful layers so it's easier to see
- Turn on any of the admin boundaries, doesn't matter which
- Zoom in to zoom level 13, and see map tile outlines appear in the same color as the admin boundary
- Zoom in further and see the lines get thicker

![image](https://user-images.githubusercontent.com/13967925/52299229-e9517e80-2952-11e9-8e49-1b94e51d7070.png)

**Comment by allthesignals** [comment] 2019-02-05 20:39
What are the steps to reproduce this? Looks like a mapbox-gl glitch.

**Comment by hannahkates** [comment] 2019-02-05 20:49
Just added steps to reproduce in the main description

**Comment by allthesignals** [comment] 2019-02-05 20:58
Thanks, yikes. I was able to reproduce this. 

I'll have to look more, but it seems like it could be something deep inside mapbox-gl. @chriswhong is there any possibility that the styling is be applied incorrectly such that it styles particular _tiles_? I know for tile-stitching, I dig down at the tile level, but I think this is only for handling of highlighting. 

One strategy would be to try some different mapbox-gl versions to see if anything changes. Another is to see if there is already an issue in mapbox-gl-js on Github - this looks very familiar.

**Comment by chriswhong** [comment] 2019-02-07 19:12
On further investigation, we discovered that this is due to a large line-width on the "glow" layers that accompany the admin boundaries layergroups.  The large admin boundaries are clipped when vector tiles are created, and the resulting chunks have the tile's boundary as part of the polygon that is being visualized.  The center of the line itself is outside of view (in the tile's buffer), but when a large line-width is applied, it bleeds into the visible part of the tile.

**Comment by chriswhong** [comment] 2019-02-07 19:59
Fixed with a PR to the layers api to optionally add buffer to the vector tiles!  https://github.com/NYCPlanning/labs-layers-api/pull/114

**Comment by chriswhong** [comment] 2019-02-07 21:13
Closed with deployment of changes to layers-api

**Closed by chriswhong** 2019-02-07 21:13 UTC
Labels: bug, to do
