### ISSUE TITLE
Export layered map to printable format

### ISSUE THREAD

**Issue by paul-chung** [NYCPlanning/labs-zola#486] opened 2018-01-11 15:11 UTC
I’m not sure if this is already implemented or if this is even the right place to ask this question, but is there a way to export map with a specific layer into a printable format?

So far all I have at my disposal are screen grabs and printing portions of the Borough I need. If there is a way to export either a polygonal selection of a layered map or even the full map with the layer on would be very helpful.

**Comment by trbmcginnis** [comment] 2018-09-13 18:38
Duplicate of #347

**Closed by trbmcginnis** 2018-09-13 18:38 UTC
Labels: enhancement, feedback
