### ISSUE TITLE
Map layers reset on first use of Mapbox geolocate

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/labs-zola#239] opened 2017-10-04 20:13 UTC
To recreate:

- Set any number of filters that are not the default state.
- Geolocate yourself

The map will refresh its filters to the default state, losing any layers that have been selected. It appears Mapbox geolocation removes any existing query params.

**Comment by allthesignals** [comment] 2017-10-05 20:16
Dupe of #221, see for follow-up.

**Closed** 2017-10-08 15:04 UTC
Labels: bug
