### ISSUE TITLE
Print - I see no ability to print like the former app

### ISSUE THREAD

**Issue by dfsavgny** [NYCPlanning/labs-zola#517] opened 2018-03-05 20:05 UTC
#### User Story
As a {type of user}, I want {some goal} so that {some reason}

#### Description
What's it all about?

#### How to reproduce this bug:

1. Step one
2. ???
3. Error

**Comment by trbmcginnis** [comment] 2018-09-13 18:40
Duplicate of #347

**Closed by trbmcginnis** 2018-09-13 18:40 UTC
Labels: enhancement, feedback
