### ISSUE TITLE
Printing Improvements for Lot View

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#449] opened 2017-12-13 00:55 UTC
Need better printing capability in Zola. Many users like to use it to print quick maps for presentations, client meetings and applications.

Great if we could incorporate actual ULURP Application Map templates for applicants.

User  Feedback:
"Will I be able to print information from the new ZOLA?"
-Burress, Duane <dburress@ngkf.com>

"I use ZoLa on a daily basis and have to print the map and property data for my clients. Is there a way to print this info from the new application? I can’t seem to find a way to do this. The old application has the print icon on the map and neatly prints all information."
-Platt-Gaston, Becky <Becky.Platt-Gaston@pzr.com>

**Comment by allthesignals** [comment] 2017-12-27 15:25
@fruchala @crosswell81 going to move this to next sprint, will need mockup and specifics for how to improve the print view cc @andycochran

**Comment by chriswhong** [comment] 2018-03-05 15:53
![Screenshot_3_5_18__10_52_AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf762a5ab781e184c78549c7e22bac205fd0e39111d0014f9121c4d4eeefc8079a6b235268d5a0ebfd23b0974c63c43a5b9834eee00a83c990dd4e8e8d51199a26867f5819d4e3714041d8bff5f33a5984fce5cf748f300.png)

For printing of lots, the map appears to be clipped versus what is on the screen, we should attempt to maximize the map area and ensure that the selected lot is centered on the print map.

**Comment by allthesignals** [comment] 2018-03-19 18:41
Using Puppeteer in a separate service (not printing locally), we can get automated outputs that look like this:
![image](https://user-images.githubusercontent.com/5004319/37615351-731fff66-2b83-11e8-9725-cd28fdefc756.png)
Or whatever we want - only problem is that PDF isn't supported. 

Do you think having a print icon would help?

**Comment by chriswhong** [comment] 2018-07-17 20:57
Explore the possibility of a lot-based controlled print layout with map and well-styled lot data.

**Comment by trbmcginnis** [comment] 2018-09-13 18:44
duplicate of #347

**Closed by trbmcginnis** 2018-09-13 18:44 UTC
Labels: enhancement, feedback
