### ISSUE TITLE
Modify street name text size for screen capture

### ISSUE THREAD

**Issue by pyanez14** [NYCPlanning/labs-zola#581] opened 2018-07-02 14:58 UTC
#### User Story
As an architect, I want to be able to modify the font size of the street names so that they are more legible when I do a screen capture

#### Description
What's it all about?  I need a screen capture of the ZOLA map when filing a project with the DOB.  Part of the information they require is seeing the name of the street, and name of the cross streets, along with the zoning classification.  It would be nice if there were a method to change the font size so that it is more legible for screen capture purposes.

#### How to reproduce this bug:

1. Step one
2. ???
3. Error

**Comment by trbmcginnis** [comment] 2018-09-13 18:45
duplicate of #347

**Closed by trbmcginnis** 2018-09-13 18:45 UTC
Labels: enhancement, feedback
