### ISSUE TITLE
Address search issue

### ISSUE THREAD

**Issue by evillagemelissa** [NYCPlanning/labs-zola#387] opened 2017-11-14 14:53 UTC
Again I am having trouble searching an address that works in the old version of Zola. **911 West End Avenue**, Manhattan, does not return any search results in the beta Zola.

**Comment by evillagemelissa** [comment] 2017-11-14 14:58
I just got the full BBL for this address by going to the old version of Zola, clicking on a link to DOF DTM, and copying the full BBL from the URL (1018910026). Is there a better way to find this?

In any case, I was able to search for the full BBL successfully on the beta Zola, which revealed that the address is listed as 915 West End Avenue. 

This is a problem that I brought up a couple of weeks ago. It seems that only one address is searchable for a property when in reality many addresses may be associated with a property.

**Comment by chriswhong** [comment] 2017-11-14 18:08
Hi @evillagemelissa, this is expected behavior, the search results you get in zola will either be matches against the `address` column of PLUTO (PLUTO does not know about 911 West End Ave), or matches against the [mapzen search api ](https://mapzen.com/products/search/geocoding/?query=&endpoint=autocomplete&lng=-73.88786&lat=40.69834&zoom=12)(which also doesn't know about 911 West End Avenue).  

You're seeing a hit in geosupport (the search that the old ZoLa uses), but we haven't been able to integrate geosupport into new ZoLa because there's no autocomplete API that would return results based on a partial address string (if you notice in old zola, you must provide an address number, street name, and borough before getting a result).

The alternatives until a geosupport web api is available will be to get a BBL through [GOAT](http://a030-goat.nyc.gov/), or zoom in on the map and click the lot you are interested in manually.

**Comment by evillagemelissa** [comment] 2017-11-15 16:51
Hopefully a web api becomes available! In the meantime, I hope the old Zola is still available to use, since that functional capacity is something I use every time I'm at the zoning helpdesk.

**Comment by smithsj** [comment] 2017-12-18 19:28
Hi @chriswhong – this is becoming a dealbreaker for me. I may have to stop using ZoLa because of this...it's making it impossible to use. One way to fix it might be to use RPAD (or is it PAD? the one with address ranges) to come up with a list of all possible addresses for every property, and then load those into the autocomplete. We at Quantierra have rolled our own this way, and while it's a bit of a pain in the ass to build, it is very good.

Another alternative is to do away with autocomplete entirely and just have it find it when you hit "search." That would definitely be preferable to it not accepting 90% of the addresses that I enter.

**Comment by chriswhong** [comment] 2017-12-18 20:35
Thanks for the feedback and the patience.  We're going to start on our own build of an API that supports autocomplete and uses PAD/geosupport under the hood.  This will be happening in January 2018, and we'd love to know a few of the addresses you're not seeing matches on (feel free to log some of them here, or compile a list on your own and provide it once we start the new geocoder project)

**Comment by chriswhong** [comment] 2017-12-26 23:51
Another address to test once we have new search working:

`1519 Decatur Street, Queens` which is known in MapPLUTO as 10-95 Irving Ave (https://zola.planning.nyc.gov/lot/4/3541/1#16.89/40.69336/-73.90184)

**Comment by evillagemelissa** [comment] 2017-12-28 14:10
Another address to test:

577 1st Avenue, New York, NY

only comes up if searched as 347 EAST 33 STREET, 10016
https://zola.planninglabs.nyc/lot/1/939/28#17.27/40.74346/-73.97236

**Comment by chriswhong** [comment] 2017-12-28 15:10
Thanks @evillagemelissa, keep them coming!

**Comment by evillagemelissa** [comment] 2018-01-23 19:34
500 Kent Avenue, Brooklyn, NY

only comes up if searched as 492 KENT AVENUE, 11249
https://zola.planninglabs.nyc/lot/3/2023/10#16.37/40.70626/-73.9658

**Comment by andycochran** [comment] 2018-02-14 20:46
Looks like all the addresses in this issue are now returning results. Closing. If you find more bad addresses, please open separate issues for each case. You can also provide feedback directly to the [NYC GeoSearch API](https://geosearch.planninglabs.nyc/feedback/). 

![image](https://user-images.githubusercontent.com/409279/36227041-c46fc78e-119d-11e8-8d2f-a3652e9b5f19.png)

![image](https://user-images.githubusercontent.com/409279/36227065-d79f7fca-119d-11e8-8b69-6671008602e2.png)

![image](https://user-images.githubusercontent.com/409279/36227078-e40ff1e0-119d-11e8-9bdb-4fb80c9d28df.png)

![image](https://user-images.githubusercontent.com/409279/36227093-ed9b7162-119d-11e8-8010-912d3a6fa702.png)

**Closed by andycochran** 2018-02-14 20:46 UTC
Labels: next sprint
