### ISSUE TITLE
Add Environmental Designation Layer

### ISSUE THREAD

**Issue by mallorygof** [NYCPlanning/labs-zola#450] opened 2017-12-14 18:20 UTC
The current Zola has an Environmental Requirements Layer, will this be incorporated into the new version?

**Comment by chriswhong** [comment] 2017-12-14 19:33
We have the dataset ready go, we just need to find a window to implement the new feature and get it deployed.  That should happen over the next couple of weeks.

**Comment by mallorygof** [comment] 2017-12-14 19:34
Great, thank you!

Mallory Goff
NYC Housing Preservation & Development
(212) 863-8462

**Comment by chriswhong** [comment] 2017-12-14 19:58
Duplicate of #375

**Closed by chriswhong** 2017-12-14 19:58 UTC
